# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndata.proto\x12\x06v2data\"\xef\x01\n\x06\x44omain\x12!\n\x04type\x18\x01 \x01(\x0e\x32\x13.v2data.Domain.Type\x12\r\n\x05value\x18\x02 \x01(\t\x12+\n\tattribute\x18\x03 \x03(\x0b\x32\x18.v2data.Domain.Attribute\x1aR\n\tAttribute\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x14\n\nbool_value\x18\x02 \x01(\x08H\x00\x12\x13\n\tint_value\x18\x03 \x01(\x03H\x00\x42\r\n\x0btyped_value\"2\n\x04Type\x12\t\n\x05Plain\x10\x00\x12\t\n\x05Regex\x10\x01\x12\n\n\x06\x44omain\x10\x02\x12\x08\n\x04\x46ull\x10\x03\"\"\n\x04\x43IDR\x12\n\n\x02ip\x18\x01 \x01(\x0c\x12\x0e\n\x06prefix\x18\x02 \x01(\r\"9\n\x05GeoIP\x12\x14\n\x0c\x63ountry_code\x18\x01 \x01(\t\x12\x1a\n\x04\x63idr\x18\x02 \x03(\x0b\x32\x0c.v2data.CIDR\")\n\tGeoIPList\x12\x1c\n\x05\x65ntry\x18\x01 \x03(\x0b\x32\r.v2data.GeoIP\"?\n\x07GeoSite\x12\x14\n\x0c\x63ountry_code\x18\x01 \x01(\t\x12\x1e\n\x06\x64omain\x18\x02 \x03(\x0b\x32\x0e.v2data.Domain\"-\n\x0bGeoSiteList\x12\x1e\n\x05\x65ntry\x18\x01 \x03(\x0b\x32\x0f.v2data.GeoSiteB\tZ\x07/v2datab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\007/v2data'
  _globals['_DOMAIN']._serialized_start=23
  _globals['_DOMAIN']._serialized_end=262
  _globals['_DOMAIN_ATTRIBUTE']._serialized_start=128
  _globals['_DOMAIN_ATTRIBUTE']._serialized_end=210
  _globals['_DOMAIN_TYPE']._serialized_start=212
  _globals['_DOMAIN_TYPE']._serialized_end=262
  _globals['_CIDR']._serialized_start=264
  _globals['_CIDR']._serialized_end=298
  _globals['_GEOIP']._serialized_start=300
  _globals['_GEOIP']._serialized_end=357
  _globals['_GEOIPLIST']._serialized_start=359
  _globals['_GEOIPLIST']._serialized_end=400
  _globals['_GEOSITE']._serialized_start=402
  _globals['_GEOSITE']._serialized_end=465
  _globals['_GEOSITELIST']._serialized_start=467
  _globals['_GEOSITELIST']._serialized_end=512
# @@protoc_insertion_point(module_scope)
